[app]
script_location = %(here)s/alembic/app
prepend_sys_path = %(here)s
path_separator = os

[business]
script_location = %(here)s/alembic/business
prepend_sys_path = %(here)s
path_separator = os

[post_write_hooks]
hooks = ruff_fix, ruff_format
ruff_fix.type = module
ruff_fix.module = ruff
ruff_fix.options = check --fix REVISION_SCRIPT_FILENAME
ruff_format.type = module
ruff_format.module = ruff
ruff_format.options = format REVISION_SCRIPT_FILENAME
